const osy=require('os')
console.log(osy.freemem())
console.log(osy.homedir())
console.log(osy.hostname())
console.log(osy.release())
console.log(osy.platform())
console.log(osy.totalmem())
console.log(osy.uptime())
console.log(osy.type())